[debug] [2018-11-28T18:02:33.787Z] ----------------------------------------------------------------------
[debug] [2018-11-28T18:02:33.789Z] Command:       /usr/local/bin/node /usr/local/bin/firebase login
[debug] [2018-11-28T18:02:33.789Z] CLI Version:   6.1.1
[debug] [2018-11-28T18:02:33.789Z] Platform:      darwin
[debug] [2018-11-28T18:02:33.789Z] Node Version:  v10.11.0
[debug] [2018-11-28T18:02:33.790Z] Time:          Wed Nov 28 2018 18:02:33 GMT+0000 (Greenwich Mean Time)
[debug] [2018-11-28T18:02:33.790Z] ----------------------------------------------------------------------
[debug] 
[info] 
[info] Visit this URL on any device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=144467489&redirect_uri=http%3A%2F%2Flocalhost%3A9006
[info] 
[info] Waiting for authentication...
[debug] [2018-11-28T18:02:39.256Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  

[debug] [2018-11-28T18:02:58.358Z] Token Fetch Error: Error
    at new FirebaseError (/usr/local/lib/node_modules/firebase-tools/lib/error.js:9:18)
    at Request._callback (/usr/local/lib/node_modules/firebase-tools/lib/api.js:28:31)
    at self.callback (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:442:20)
    at Request.onRequestError (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:182:13)
    at ClientRequest.EventEmitter.emit (domain.js:442:20)
    at TLSSocket.socketErrorListener (_http_client.js:391:9)
    at TLSSocket.emit (events.js:182:13)
